### ISSUE TITLE
errors in promises are ignored

### ISSUE THREAD

**Issue by johanneswilm** [jojax/django-js-error-hook#11]
This is a major problem: errors are ignored if they are in promises. We need to start listening to unhandled rejections [1]. This is imperfect as it only works in Chrome, but it's better than nothing.

[1] https://developer.mozilla.org/en-US/docs/Web/Events/unhandledrejection

**Comment by Natim** [comment]
Can I let you file a pull-request about that?

**Comment by johanneswilm** [comment]
Yes, unless you plan on adding something, I was thinking of filing one.

**Comment by johanneswilm** [comment]
Fixed in 0.6
